title: From Electrician to Web Developer 
author: r83wheeler
email: r83wheeler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal journey from Electrician to Web Developer as a 37 year old. 

# social links
twitter_username: RussWheelernow # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/r83wheeler # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
